import { Achievement } from '../models/achievement';
import { ACHIEVEMENT_EVENT } from '../interfaces/achievements';

export const achievementsBase: Omit<Achievement, '_id' | 'user'>[] = [
  {
    title: 'Chess mover',
    total: 100,
    current: 0,
    description: 'Make 100 chess moves',
    avatar: 'achievements/chess-player.png',
    event: ACHIEVEMENT_EVENT.MOVE_CHESS,
  },
  {
    title: 'Chess player',
    total: 10,
    current: 0,
    description: 'Play 10 chess games',
    avatar: 'achievements/chess-player.png',
    event: ACHIEVEMENT_EVENT.PLAY_CHESS_GAME,
  },
  {
    title: 'Chess winner',
    total: 10,
    current: 0,
    description: 'Win 10 chess games',
    avatar: 'achievements/chess-winner.png',
    event: ACHIEVEMENT_EVENT.WIN_CHESS_GAME,
  },
  {
    title: 'Chess loser',
    total: 10,
    current: 0,
    description: 'Lose 10 chess games',
    avatar: 'achievements/chess-loser.png',
    event: ACHIEVEMENT_EVENT.LOSE_CHESS_GAME,
  },
  {
    title: 'Checkers mover',
    total: 100,
    current: 0,
    description: 'Make 100 checkers moves',
    avatar: 'achievements/checkers-player.png',
    event: ACHIEVEMENT_EVENT.MOVE_CHECKERS,
  },
  {
    title: 'Checkers player',
    total: 10,
    current: 0,
    description: 'Play 10 checkers games',
    avatar: 'achievements/checkers-loser.png',
    event: ACHIEVEMENT_EVENT.PLAY_CHECKERS_GAME,
  },
  {
    title: 'Checkers winner',
    total: 10,
    current: 0,
    description: 'Win 10 checkers games',
    avatar: 'achievements/checkers-winner.png',
    event: ACHIEVEMENT_EVENT.WIN_CHECKERS_GAME,
  },
  {
    title: 'Checkers loser',
    total: 10,
    current: 0,
    description: 'Lose 10 checkers games',
    avatar: 'achievements/checkers-player.png',
    event: ACHIEVEMENT_EVENT.LOSE_CHECKERS_GAME,
  },
  {
    title: 'Legend',
    total: 1,
    current: 0,
    description: 'Register on the platform',
    avatar: 'achievements/checkers-winner.png',
    event: ACHIEVEMENT_EVENT.REGISTER,
  },
  {
    title: 'Daily login',
    total: 20,
    current: 0,
    description: 'Login 20 times',
    avatar: 'achievements/checkers-player.png',
    event: ACHIEVEMENT_EVENT.LOGIN,
  },
];
